name: clustering
channels:
  - conda-forge
  - anaconda-fusion
  - defaults
dependencies:
  - hdbscan=0.8.12
  - cython=0.27.3
  - jupyter=1.0.0
  - matplotlib=2.2.0
  - numpy=1.14.1
  - python=3.6.4
  - scikit-learn=0.19.1
  - scipy=1.0.0
  - seaborn=0.8.1